import light1 from "../assets/images/light/1.jpeg";
import light2 from "../assets/images/light/2.jpeg";
import light3 from "../assets/images/light/3.jpeg";
import light4 from "../assets/images/light/4.jpeg";
import light5 from "../assets/images/light/5.jpeg";
import light6 from "../assets/images/light/6.jpeg";
import light7 from "../assets/images/light/7.jpeg";
import light8 from "../assets/images/light/8.jpeg";
import light9 from "../assets/images/light/9.jpeg";
import light10 from "../assets/images/light/10.jpeg";
import light11 from "../assets/images/light/11.jpeg";
import light12 from "../assets/images/light/12.jpeg";
import light13 from "../assets/images/light/13.jpeg";
import light14 from "../assets/images/light/14.jpeg";
import light15 from "../assets/images/light/15.jpeg";
import light16 from "../assets/images/light/16.jpeg";
import light17 from "../assets/images/light/17.jpeg";
import light18 from "../assets/images/light/18.jpeg";
import light19 from "../assets/images/light/19.jpeg";
import light20 from "../assets/images/light/20.jpeg";
import light21 from "../assets/images/light/21.jpeg";
// import light22 from "../assets/images/light/22.jpeg";
// import light23 from "../assets/images/light/23.jpeg";
// import light24 from "../assets/images/light/24.jpeg";


export const DATA = [
  {
    id: "1",
    name: "Classic Table Lamp",
    price: 45.99,
    views: 1200,
    comments: 35,
    img: light1,
    description: "A classic table lamp with a wooden base and fabric shade.",
    category: "Table Lamp",
    rating: 4.3,
    availability: "In stock",
    dimensions: { width: "30cm", height: "50cm" },
    weight: "1.5kg",
    wattage: "60W",
    numberOfBulbs: 1,
    material: "Wood and Fabric",
    warranty: "2 years",
    specialFeatures: ["Dimmable", "Energy Efficient"],
    dateAdded: "2024-09-25",
  },
  {
    id: "2",
    name: "Modern Floor Lamp",
    price: 89.5,
    views: 950,
    comments: 42,
    img: light2,
    description: "A sleek modern floor lamp perfect for contemporary spaces.",
    category: "Floor Lamp",
    rating: 4.6,
    availability: "In stock",
    dimensions: { width: "40cm", height: "160cm" },
    weight: "2.3kg",
    wattage: "75W",
    numberOfBulbs: 1,
    material: "Metal",
    warranty: "3 years",
    specialFeatures: ["Adjustable height", "LED compatible"],
    dateAdded: "2024-09-25",
  },
  {
    id: "3",
    name: "Elegant Chandelier",
    price: 199.99,
    views: 500,
    comments: 22,
    img: light3,
    description: "A stunning chandelier that adds elegance to any room.",
    category: "Chandelier",
    rating: 4.7,
    availability: "Out of stock",
    dimensions: { width: "80cm", height: "120cm" },
    weight: "5kg",
    wattage: "100W",
    numberOfBulbs: 6,
    material: "Crystal and Metal",
    warranty: "5 years",
    specialFeatures: ["Remote control", "Dimmable"],
    dateAdded: "2024-09-25",
  },
  {
    id: "4",
    name: "Minimalist Desk Light",
    price: 34.75,
    views: 1500,
    comments: 50,
    img: light4,
    description:
      "A minimalist desk lamp with a modern design and soft lighting.",
    category: "Desk Lamp",
    rating: 4.4,
    availability: "In stock",
    dimensions: { width: "25cm", height: "45cm" },
    weight: "1kg",
    wattage: "40W",
    numberOfBulbs: 1,
    material: "Plastic and Metal",
    warranty: "1 year",
    specialFeatures: ["USB charging port", "Touch control"],
    dateAdded: "2024-09-25",
  },
  {
    id: "5",
    name: "Luxury Pendant Light",
    price: 120.0,
    views: 800,
    comments: 15,
    img: light5,
    description:
      "A luxury pendant light that brings a sophisticated look to any room.",
    category: "Pendant Light",
    rating: 4.8,
    availability: "In stock",
    dimensions: { width: "50cm", height: "75cm" },
    weight: "3.5kg",
    wattage: "90W",
    numberOfBulbs: 3,
    material: "Glass and Metal",
    warranty: "4 years",
    specialFeatures: ["Energy Efficient", "Dimmable"],
    dateAdded: "2024-09-25",
  },
  {
    id: "6",
    name: "Vintage Wall Sconce",
    price: 55.0,
    views: 600,
    comments: 18,
    img: light6,
    description: "A vintage-style wall sconce perfect for retro-themed spaces.",
    category: "Wall Sconce",
    rating: 4.2,
    availability: "In stock",
    dimensions: { width: "20cm", height: "35cm" },
    weight: "1.2kg",
    wattage: "40W",
    numberOfBulbs: 1,
    material: "Brass and Glass",
    warranty: "2 years",
    specialFeatures: ["Dimmable", "Easy installation"],
    dateAdded: "2024-09-25",
  },
  {
    id: "7",
    name: "Industrial Ceiling Light",
    price: 80.0,
    views: 700,
    comments: 20,
    img: light7,
    description:
      "An industrial-style ceiling light with a rugged and modern look.",
    category: "Ceiling Light",
    rating: 4.5,
    availability: "In stock",
    dimensions: { width: "40cm", height: "60cm" },
    weight: "2.8kg",
    wattage: "80W",
    numberOfBulbs: 4,
    material: "Metal",
    warranty: "3 years",
    specialFeatures: ["Water-resistant", "Energy Efficient"],
    dateAdded: "2024-09-25",
  },
  {
    id: "8",
    name: "Rustic Table Lamp",
    price: 65.0,
    views: 900,
    comments: 30,
    img: light8,
    description: "A rustic table lamp made from natural wood and iron.",
    category: "Table Lamp",
    rating: 4.3,
    availability: "In stock",
    dimensions: { width: "28cm", height: "55cm" },
    weight: "1.7kg",
    wattage: "60W",
    numberOfBulbs: 1,
    material: "Wood and Iron",
    warranty: "2 years",
    specialFeatures: ["Eco-friendly", "Handcrafted"],
    dateAdded: "2024-09-25",
  },
  {
    id: "9",
    name: "Contemporary Pendant Light",
    price: 110.0,
    views: 850,
    comments: 25,
    img: light9,
    description: "A contemporary pendant light perfect for modern homes.",
    category: "Pendant Light",
    rating: 4.7,
    availability: "In stock",
    dimensions: { width: "60cm", height: "90cm" },
    weight: "4kg",
    wattage: "100W",
    numberOfBulbs: 5,
    material: "Glass and Metal",
    warranty: "4 years",
    specialFeatures: ["Adjustable length", "Energy Efficient"],
    dateAdded: "2024-09-25",
  },
  {
    id: "10",
    name: "Retro Floor Lamp",
    price: 95.0,
    views: 650,
    comments: 28,
    img: light10,
    description: "A retro-style floor lamp with a unique design.",
    category: "Floor Lamp",
    rating: 4.5,
    availability: "In stock",
    dimensions: { width: "35cm", height: "160cm" },
    weight: "2.5kg",
    wattage: "70W",
    numberOfBulbs: 1,
    material: "Metal",
    warranty: "3 years",
    specialFeatures: ["Adjustable head", "LED compatible"],
    dateAdded: "2024-09-25",
  },
  {
    id: "11",
    name: "Art Deco Table Lamp",
    price: 75.0,
    views: 700,
    comments: 32,
    img: light11,
    description: "An elegant Art Deco table lamp with intricate detailing.",
    category: "Table Lamp",
    rating: 4.4,
    availability: "In stock",
    dimensions: { width: "30cm", height: "50cm" },
    weight: "1.6kg",
    wattage: "60W",
    numberOfBulbs: 1,
    material: "Brass and Fabric",
    warranty: "2 years",
    specialFeatures: ["Energy Efficient", "Dimmable"],
    dateAdded: "2024-09-25",
  },
  {
    id: "12",
    name: "Modern Wall Light",
    price: 50.0,
    views: 1000,
    comments: 22,
    img: light12,
    description: "A sleek modern wall light with a clean, minimal design.",
    category: "Wall Light",
    rating: 4.2,
    availability: "In stock",
    dimensions: { width: "20cm", height: "35cm" },
    weight: "1kg",
    wattage: "40W",
    numberOfBulbs: 1,
    material: "Metal and Glass",
    warranty: "1 year",
    specialFeatures: ["Dimmable", "LED compatible"],
    dateAdded: "2024-09-25",
  },
  {
    id: "13",
    name: "Scandinavian Floor Lamp",
    price: 85.0,
    views: 900,
    comments: 40,
    img: light13,
    description: "A Scandinavian-style floor lamp with a minimalist aesthetic.",
    category: "Floor Lamp",
    rating: 4.6,
    availability: "In stock",
    dimensions: { width: "40cm", height: "150cm" },
    weight: "2.3kg",
    wattage: "70W",
    numberOfBulbs: 1,
    material: "Wood and Fabric",
    warranty: "2 years",
    specialFeatures: ["Eco-friendly", "LED compatible"],
    dateAdded: "2024-09-25",
  },
  {
    id: "14",
    name: "Classic Chandeliers",
    price: 210.0,
    views: 400,
    comments: 14,
    img: light14,
    description: "A large classic chandelier perfect for grand rooms.",
    category: "Chandelier",
    rating: 4.9,
    availability: "Out of stock",
    dimensions: { width: "90cm", height: "130cm" },
    weight: "7kg",
    wattage: "120W",
    numberOfBulbs: 8,
    material: "Crystal and Metal",
    warranty: "5 years",
    specialFeatures: ["Remote control", "Dimmable"],
    dateAdded: "2024-09-25",
  },
  {
    id: "15",
    name: "Sleek Desk Light",
    price: 40.0,
    views: 1200,
    comments: 45,
    img: light15,
    description: "A sleek and stylish desk light with a flexible arm.",
    category: "Desk Lamp",
    rating: 4.5,
    availability: "In stock",
    dimensions: { width: "25cm", height: "45cm" },
    weight: "1kg",
    wattage: "40W",
    numberOfBulbs: 1,
    material: "Metal",
    warranty: "1 year",
    specialFeatures: ["USB charging port", "Touch control"],
    dateAdded: "2024-09-25",
  },
  {
    id: "16",
    name: "Elegant Wall Light",
    price: 65.0,
    views: 800,
    comments: 20,
    img: light16,
    description:
      "An elegant wall light perfect for adding sophistication to any room.",
    category: "Wall Light",
    rating: 4.3,
    availability: "In stock",
    dimensions: { width: "22cm", height: "30cm" },
    weight: "1.2kg",
    wattage: "50W",
    numberOfBulbs: 2,
    material: "Metal and Glass",
    warranty: "2 years",
    specialFeatures: ["Dimmable", "Energy Efficient"],
    dateAdded: "2024-09-25",
  },
  {
    id: "17",
    name: "Chic Pendant Lamp",
    price: 130.0,
    views: 750,
    comments: 30,
    img: light17,
    description: "A chic pendant lamp that adds elegance to dining areas.",
    category: "Pendant Light",
    rating: 4.8,
    availability: "In stock",
    dimensions: { width: "50cm", height: "80cm" },
    weight: "3kg",
    wattage: "90W",
    numberOfBulbs: 3,
    material: "Glass and Metal",
    warranty: "3 years",
    specialFeatures: ["Adjustable height", "LED compatible"],
    dateAdded: "2024-09-25",
  },
  {
    id: "18",
    name: "Compact Desk Lamp",
    price: 55.0,
    views: 950,
    comments: 25,
    img: light18,
    description: "A compact desk lamp perfect for small workspaces.",
    category: "Desk Lamp",
    rating: 4.4,
    availability: "In stock",
    dimensions: { width: "20cm", height: "40cm" },
    weight: "1.1kg",
    wattage: "40W",
    numberOfBulbs: 1,
    material: "Plastic and Metal",
    warranty: "1 year",
    specialFeatures: ["Dimmable", "Touch control"],
    dateAdded: "2024-09-25",
  },
  {
    id: "19",
    name: "Luxury Floor Light",
    price: 140.0,
    views: 700,
    comments: 15,
    img: light19,
    description: "A luxury floor light with an opulent design.",
    category: "Floor Lamp",
    rating: 4.7,
    availability: "In stock",
    dimensions: { width: "45cm", height: "160cm" },
    weight: "3kg",
    wattage: "80W",
    numberOfBulbs: 2,
    material: "Metal and Glass",
    warranty: "4 years",
    specialFeatures: ["Adjustable light settings", "Remote control"],
    dateAdded: "2024-09-25",
  },
  {
    id: "20",
    name: "Modern Chandelier",
    price: 180.0,
    views: 600,
    comments: 20,
    img: light20,
    description: "A modern chandelier that adds style to large rooms.",
    category: "Chandelier",
    rating: 4.6,
    availability: "In stock",
    dimensions: { width: "85cm", height: "120cm" },
    weight: "5.5kg",
    wattage: "100W",
    numberOfBulbs: 6,
    material: "Metal and Crystal",
    warranty: "4 years",
    specialFeatures: ["Energy efficient", "Dimmable"],
    dateAdded: "2024-09-25",
  },
  {
    id: "21",
    name: "Vintage Desk Light",
    price: 70.0,
    views: 850,
    comments: 35,
    img: light21,
    description:
      "A vintage desk light that brings a classic feel to your workspace.",
    category: "Desk Lamp",
    rating: 4.4,
    availability: "In stock",
    dimensions: { width: "30cm", height: "50cm" },
    weight: "1.4kg",
    wattage: "60W",
    numberOfBulbs: 1,
    material: "Brass and Glass",
    warranty: "2 years",
    specialFeatures: ["Adjustable arm", "LED compatible"],
    dateAdded: "2024-09-25",
  },
  // {
  //   id: "22",
  //   name: "Sculptural Table Lamp",
  //   price: 90.0,
  //   views: 800,
  //   comments: 22,
  //   img: light22,
  // },
  // {
  //   id: "23",
  //   name: "Bright Pendant Light",
  //   price: 115.0,
  //   views: 650,
  //   comments: 27,
  //   img: light23,
  // },
  // {
  //   id: "24",
  //   name: "Artistic Floor Lamp",
  //   price: 100.0,
  //   views: 750,
  //   comments: 18,
  //   img: light24,
  // },
];
